# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# COMENTARIO
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      #- run:
      #    name: Carpeta Tests
      #    command: . classes/test.cls
      - run:
          name: Validate Components & Run Tests
          no_output_timeout: 5m
          mkdir -p /tmp/test-results
          command: . build/test.sh
      - store_test_results:
          path: test-results
  deploy-prod:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to PRUEBA
          command: . build/setup-prod.sh
         # - run:
          # name: Deploy to PRUEBA
           #command: . build/deploy-prod.sh
workflows:
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy-prod:
          filters:
            branches:
              only:
                - Master
